name: Publish GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@casamagalhaes'
    - run: yarn
    - run: yarn build
    - run: npm --no-git-tag-version version $RELEASE_TAG_NAME
      env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}